/**
 * Curated list of Builder Titles for HH Goa 2026 V2
 * From the V2 Implementation Doc
 */
export const BUILDER_TITLES = [
  "THE PIXEL ALCHEMIST",
  "VIBE ENGINEER",
  "FULL STACK GREMLIN",
  "PROMPT WHISPERER",
  "API ABUSER",
  "SERIAL SIDE PROJECTER",
  "BROKE PROD ONCE",
  "NEVER READ THE DOCS",
  "CEO OF SIDE PROJECTS",
  "CAFFEINATED CODER",
  "DEBUGGING IN PROD",
  "ONE MORE FEATURE",
  "DESIGN? WHAT DESIGN",
  "JUST SHIP IT",
  "LIVING IN MY TERMINAL",
  "LOCALHOST LEGEND",
  "MVP FACTORY",
  "GIT PUSH THERAPIST",
  "ZERO TO DEPLOYED",
  "BUILDING IN PUBLIC",
  "CHAOS AGENT CERTIFIED",
  "JUGAAD ENGINEER",
  "WILL SHIP FOR CHAI",
  "404: SLEEP NOT FOUND"
];

/**
 * Default builder title to use when none selected
 */
export const DEFAULT_BUILDER_TITLE = "BUILDER";

export default BUILDER_TITLES;
